version: '3'

services:

  graphdb:
    build:
      context: .
      dockerfile: docker/graphdb/Dockerfile
    volumes:
      - "./data/graphdb-import:/root/graphdb-import"
    tty: true
    stdin_open: true
    ports: 
      - "7200:7200"

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - "./data:/var/lib/mysql"
      - "./config:/config"
      - "./scripts:/scripts"
    command: bash -c 'dos2unix scripts/umls2MySql.sh && sh scripts/umls2MySql.sh'
    tty: true
    stdin_open: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'umls_db'
    env_file:
      - ./config/config.env

  builder:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    volumes:
      - "./data/:/data"
      - "./config:/config"
      - "./scripts:/scripts"
      - "./R:/R"
    command: bash -c 'dos2unix scripts/master_builder.sh && sh scripts/master_builder.sh'
    tty: true
    stdin_open: true
    env_file:
      - ./config/config.env
    depends_on:
      - graphdb
      - mysql
