PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select 
distinct 
#?m ?rewriteGraph ?assertedPredicate ?i10code
?m ?axPred ?apl ?axVal ?avl
where {
    graph <http://example.com/resource/MondoTransitiveSubClasses> {
        ?m rdfs:subClassOf <http://purl.obolibrary.org/obo/MONDO_0000001> .
    }
    graph ?rewriteGraph {
        ?m ?assertedPredicate ?i10
    }
    graph <http://example.com/resource/ICD10TransitiveSubClasses> {
        ?i10 rdfs:subClassOf ?anythingIcd10 .
    }
    graph <http://purl.bioontology.org/ontology/ICD10CM/> {
        ?i10 skos:notation ?i10code
    }
    graph <http://example.com/resource/MondoTransitiveSubClasses> {
        ?m rdfs:subClassOf ?msuper .
    }
    graph <http://example.com/resource/materializedSimpleMondoAxioms> {
        ?msuper ?axPred ?axVal
    }
    graph <http://purl.obolibrary.org/obo/mondo.owl> {
        optional {
            ?axPred rdfs:label ?apl .
        }
        optional {
            ?axVal rdfs:label ?avl .
        }
    }
}
